const SAVE_AUTHENTICATION = 'SAVE_AUTHENTICATION';
const CLEAR_AUTHENTICATION = 'CLEAR_AUTHENTICATION';
const LOGOUT = 'LOGOUT';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAIL = 'LOGOUT_FAIL';

export { CLEAR_AUTHENTICATION, LOGOUT, LOGOUT_FAIL, LOGOUT_SUCCESS, SAVE_AUTHENTICATION };
